export interface Mill {
  id: string
  name: string
  company: string
  lat: number
  lng: number
  status: 'operating' | 'closed' | 'suspended'
  capacity: string
  efficiency: number
  throughput: string
  maintenanceAlert?: string
  notes?: string
  cogenMW?: number
}

export const mills: Mill[] = [
  {
    id: 'sezela',
    name: 'Sezela',
    company: 'Illovo Sugar',
    lat: -30.4102,
    lng: 30.6772,
    status: 'operating',
    capacity: '300 TCH',
    efficiency: 94.2,
    throughput: '2.1M tonnes/season',
    cogenMW: 15,
    maintenanceAlert: 'Turbine service due in 3 weeks',
  },
  {
    id: 'eston',
    name: 'Eston',
    company: 'Illovo Sugar',
    lat: -29.8705,
    lng: 30.5289,
    status: 'operating',
    capacity: '220 TCH',
    efficiency: 91.8,
    throughput: '1.4M tonnes/season',
    cogenMW: 8,
  },
  {
    id: 'noodsberg',
    name: 'Noodsberg',
    company: 'Illovo Sugar',
    lat: -29.3595,
    lng: 30.6884,
    status: 'operating',
    capacity: '240 TCH',
    efficiency: 93.1,
    throughput: '1.6M tonnes/season',
    cogenMW: 10,
  },
  {
    id: 'umzimkulu',
    name: 'Umzimkulu',
    company: 'Illovo Sugar',
    lat: -30.7359,
    lng: 30.4539,
    status: 'closed',
    capacity: '150 TCH',
    efficiency: 0,
    throughput: 'Closed',
    notes: 'Permanently closed in 2021 — cane redirected to Sezela',
  },
  {
    id: 'maidstone',
    name: 'Maidstone',
    company: 'Tongaat Hulett',
    lat: -29.5501,
    lng: 31.1307,
    status: 'operating',
    capacity: '300 TCH',
    efficiency: 89.5,
    throughput: '1.9M tonnes/season',
    cogenMW: 12,
    maintenanceAlert: 'Crusher bearing temperature rising — monitor closely',
    notes: 'Under Tongaat Hulett business rescue',
  },
  {
    id: 'amatikulu',
    name: 'Amatikulu',
    company: 'Tongaat Hulett',
    lat: -29.0459,
    lng: 31.5266,
    status: 'operating',
    capacity: '240 TCH',
    efficiency: 90.3,
    throughput: '1.5M tonnes/season',
    cogenMW: 9,
    notes: 'Under Tongaat Hulett business rescue',
  },
  {
    id: 'felixton',
    name: 'Felixton',
    company: 'Tongaat Hulett',
    lat: -28.8358,
    lng: 31.8924,
    status: 'operating',
    capacity: '280 TCH',
    efficiency: 91.7,
    throughput: '1.8M tonnes/season',
    cogenMW: 11,
    notes: 'Under Tongaat Hulett business rescue',
  },
  {
    id: 'darnall',
    name: 'Darnall',
    company: 'Tongaat Hulett',
    lat: -29.2705,
    lng: 31.3597,
    status: 'closed',
    capacity: '200 TCH',
    efficiency: 0,
    throughput: 'Mothballed',
    notes: 'Mothballed indefinitely since 2020 — cane redirected to Amatikulu & Maidstone',
  },
  {
    id: 'komati',
    name: 'Komati',
    company: 'RCL Foods',
    lat: -25.6115,
    lng: 31.8709,
    status: 'operating',
    capacity: '380 TCH',
    efficiency: 92.8,
    throughput: '2.4M tonnes/season',
    cogenMW: 18,
  },
  {
    id: 'malelane',
    name: 'Malelane',
    company: 'RCL Foods',
    lat: -25.4645,
    lng: 31.5622,
    status: 'operating',
    capacity: '320 TCH',
    efficiency: 93.5,
    throughput: '2.0M tonnes/season',
    cogenMW: 14,
  },
  {
    id: 'pongola',
    name: 'Pongola',
    company: 'RCL Foods',
    lat: -27.3957,
    lng: 31.6600,
    status: 'operating',
    capacity: '260 TCH',
    efficiency: 91.2,
    throughput: '1.7M tonnes/season',
    cogenMW: 10,
  },
  {
    id: 'gledhow',
    name: 'Gledhow',
    company: 'Gledhow Sugar Company',
    lat: -29.3626,
    lng: 31.2893,
    status: 'operating',
    capacity: '200 TCH',
    efficiency: 88.9,
    throughput: '1.2M tonnes/season',
    cogenMW: 6,
    maintenanceAlert: 'Diffuser refurbishment planned for off-season',
  },
  {
    id: 'umfolozi',
    name: 'Umfolozi',
    company: 'Umfolozi Sugar Mill',
    lat: -28.4059,
    lng: 32.2143,
    status: 'operating',
    capacity: '220 TCH',
    efficiency: 90.1,
    throughput: '1.3M tonnes/season',
    cogenMW: 7,
  },
  {
    id: 'dalton',
    name: 'UCL Dalton',
    company: 'UCL Company',
    lat: -29.3385,
    lng: 30.6272,
    status: 'operating',
    capacity: '180 TCH',
    efficiency: 89.7,
    throughput: '1.1M tonnes/season',
    cogenMW: 5,
  },
]

// CTS (Cane Testing Service) labs — co-located at each operating mill
// 9 in KZN + 2 in Mpumalanga = 11 total
export const ctsLabs = [
  { millId: 'sezela', name: 'CTS Sezela', region: 'KZN' },
  { millId: 'eston', name: 'CTS Eston', region: 'KZN' },
  { millId: 'noodsberg', name: 'CTS Noodsberg', region: 'KZN' },
  { millId: 'maidstone', name: 'CTS Maidstone', region: 'KZN' },
  { millId: 'amatikulu', name: 'CTS Amatikulu', region: 'KZN' },
  { millId: 'felixton', name: 'CTS Felixton', region: 'KZN' },
  { millId: 'gledhow', name: 'CTS Gledhow', region: 'KZN' },
  { millId: 'umfolozi', name: 'CTS Umfolozi', region: 'KZN' },
  { millId: 'pongola', name: 'CTS Pongola', region: 'KZN' },
  { millId: 'komati', name: 'CTS Komati', region: 'Mpumalanga' },
  { millId: 'malelane', name: 'CTS Malelane', region: 'Mpumalanga' },
]

export const millRegions = [
  { name: 'KwaZulu-Natal South Coast', mills: ['sezela', 'umzimkulu'], color: '#22c55e' },
  { name: 'KwaZulu-Natal Midlands', mills: ['eston', 'noodsberg', 'dalton'], color: '#3b82f6' },
  { name: 'KwaZulu-Natal North Coast', mills: ['maidstone', 'amatikulu', 'felixton', 'darnall', 'gledhow'], color: '#f59e0b' },
  { name: 'Zululand', mills: ['umfolozi', 'pongola'], color: '#a855f7' },
  { name: 'Mpumalanga', mills: ['komati', 'malelane'], color: '#ef4444' },
]
